### PR TITLE
Moves to suggested library pattern. Closes #11

### LINKED ISSUE #11: Standardize on Library Pattern
I know we chuckled a little bit about AMD support and all that jazz but I'd like to move to the pattern here: 

http://stackoverflow.com/a/6824210

### PR DESCRIPTION
**Pull request by creade**

### CODE REVIEW

**Comment by bsmithgall** [comment]
:+1: for now, I'm going to ask that you hold off on merging for the moment -- I'd like to get some basic testing/continuous integration set up to start testing larger changes against (as part of work on #4).

**Comment by creade** [comment]
Makes sense. Tests were going to be my next thing to tackle. I'll open an edit on #4 for picking a js test framework?

**Comment by bsmithgall** [comment]
Do you have preferences? Here were my needs:
- Good integration with Grunt
- Not too awful to set up/write
- Potentially decent integration with frameworks down the line as we think about booting up the editor

**Comment by mapsam** [comment]
I've had good luck with [Karma](https://github.com/cugos/dropchop/tree/master/spec)! We are using it in [dropchop](https://github.com/cugos/dropchop/blob/master/Gruntfile.js#L86-L90), which relies on Grunt (therefore using [`grunt-karma`](https://github.com/karma-runner/grunt-karma)). Setup [isn't too bad](https://github.com/cugos/dropchop/blob/master/spec/karma.conf.js).

**Comment by creade** [comment]
That looks v. rad. The tests themselves are in [Mocha](http://mochajs.org/) though right?

**Comment by mapsam** [comment]
Uh, yes you are right @creade! Also using `chai`, `sinon`, and `browserify` in there. So maybe better put: We are using Karma as our testing task runner. (this entire sentence is absurd)

I personally feel like it becomes overkill sometimes - but it allows us to chain some UI tests with other tests, which is neat. We might be better off only choosing a single testing framework for now?

**Comment by bsmithgall** [comment]
Closing this because I stole all of your code in #14 @creade !

**Pull request closed without merging**
